plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/mnt/c/Users/Usuario/Desktop/suellen-pages"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]